import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Robolaunch GRPC-Web</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="http://robolaunch.io">Robolaunch</a>
        </h1>

        <p className={styles.description}>Example GRPC Web</p>

        <div className={styles.grid}>
          <a href="#" className={styles.card}>
            <h2>Delete User &rarr;</h2>
            <p>gRPC Call for delete user!</p>
            <button onClick={() => alert("stop")}>Click me!</button>
          </a>

          <a href="#" className={styles.card}>
            <h2>Create User &rarr;</h2>
            <p>gRPC Call for create user!</p>

            <button onClick={() => alert("stop")}>Click me!</button>
          </a>

          <a href="#" className={styles.card}>
            <h2>Create Service &rarr;</h2>
            <button onClick={() => alert("stop")}>Click me!</button>
          </a>
          <a href="#" className={styles.card}>
            <h2>Delete Service &rarr;</h2>
            <button onClick={() => alert("stop")}>Click me!</button>
          </a>
        </div>
      </main>
    </div>
  );
};

export default Home;
