apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.robot }}-start
  namespace: robot-test-1
data:
  {{ .Values.robot }}_start.sh: |
    {{ .Files.Get "launch_sim.sh" | nindent 4 }}
---	
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.robot }}-supervisord
  namespace: robot-test-1
data:
  {{ .Values.robot }}_supervisord.conf: |
    [program:{{ .Values.robot }}]
    environment=HOME="/home/%(ENV_USER)s",USER="%(ENV_USER)s"
    user=%(ENV_USER)s
    command=/etc/provedge/{{ .Values.robot }}_start.sh
    autorestart=true
    priority=900
    stdout_logfile=/tmp/{{ .Values.robot }}.log
    stdout_logfile_maxbytes=100MB
    stdout_logfile_backups=10
    redirect_stderr=true
